query IssuesQuery($owner: String!, $proj_num: Int!, $cursor: String!) {
  organization(login: $owner) {
    projectV2(number: $proj_num) {
      id
      title
      items(first: 100, after: $cursor) {
 		__typename       
        totalCount
        pageInfo {
          endCursor
        }
        nodes {
          id
          __typename
          content {
            __typename
            ... on DraftIssue {
              __typename
              createdAt
              title
              creator {
                __typename
                login
              }
            }
            ... on Issue {
              __typename
              createdAt
              title
              author {
                __typename
                login
              }
            }
          }
        }
      }
    }
  }
}